# Generated by Django 4.1.6 on 2023-02-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='date_create_at',
            new_name='date_create_adress',
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='date_update_at',
            new_name='date_update_adress',
        ),
    ]
