# Generated by Django 4.1.6 on 2023-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komunaldata',
            options={'ordering': ['-date_update', '-date_create'], 'verbose_name_plural': 'Показания счётчиков'},
        ),
        migrations.RemoveField(
            model_name='komunaldata',
            name='komunaldata_dateoff',
        ),
        migrations.AlterField(
            model_name='komunaldata',
            name='komunaldata_dateon',
            field=models.DateField(verbose_name='Данные за месяц'),
        ),
    ]
