# Generated by Django 4.1.6 on 2023-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0002_alter_myuser_options_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='adress',
            field=models.ManyToManyField(related_name='adress_of_user', to='app_komunalka.adress'),
        ),
    ]
