# Generated by Django 4.1.6 on 2023-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0003_myuser_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='user',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='adress',
            field=models.ManyToManyField(related_name='adress_of_user', to='app_komunalka.adress', verbose_name='Адрес'),
        ),
    ]
