# Generated by Django 4.1.6 on 2023-04-09 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0003_alter_komunaldata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komunaldata',
            name='komunaldata_dateon',
            field=models.DateField(default=datetime.date, verbose_name='Данные за месяц'),
        ),
    ]
