# Generated by Django 4.1.6 on 2023-02-13 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0004_remove_adress_user_alter_myuser_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='user',
            field=models.ManyToManyField(related_name='users_adress', to=settings.AUTH_USER_MODEL),
        ),
    ]
