# Generated by Django 4.1.6 on 2023-02-13 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0005_adress_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['country', 'city', 'street', 'house', 'corps', 'room'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_adress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KomunalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.PositiveIntegerField()),
                ('water', models.PositiveIntegerField()),
                ('light', models.PositiveIntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress_komunaldata', to='app_komunalka.adress', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Комунальные показания счётчиков',
                'ordering': ['date_update', 'date_create'],
            },
        ),
    ]
