# Generated by Django 4.1.6 on 2023-04-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0006_alter_komunaldata_komunaldata_dateon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komunaldata',
            name='komunaldata_dateon',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 26), null=True, verbose_name='Данные за месяц'),
        ),
        migrations.AlterUniqueTogether(
            name='adress',
            unique_together={('country', 'city', 'street', 'house', 'corps', 'room')},
        ),
    ]
