# Generated by Django 4.1.6 on 2023-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0006_alter_adress_options_alter_adress_user_komunaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komunaldata',
            options={'ordering': ['date_update', 'date_create'], 'verbose_name_plural': 'Показания счётчиков'},
        ),
        migrations.AlterField(
            model_name='komunaldata',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
