# Generated by Django 4.1.6 on 2023-04-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0007_alter_komunaldata_komunaldata_dateon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adress',
            unique_together={('country', 'city', 'street', 'house', 'room')},
        ),
    ]
