# Generated by Django 4.1.6 on 2023-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0007_alter_komunaldata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adress',
            field=models.ManyToManyField(blank=True, null=True, related_name='adress_of_user', to='app_komunalka.adress', verbose_name='Адрес'),
        ),
    ]
