# Generated by Django 4.1.6 on 2023-07-09 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_komunalka', '0008_alter_adress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komunaldata',
            name='komunaldata_dateon',
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 9), null=True, verbose_name='Данные за месяц'),
        ),
    ]
